server:
  port: 8871
spring:
  application:
    name: example
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/example
    username: admin
    password: 1RNbTI@m$zIE114s
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true

